spring:
  # 环境 dev|test|prod
  profiles:
    active: test

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: cc.mrbird.febs.api.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

febs:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /api/s-user/login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 3600

weChat:
  app_id: wxcbb6f0ef4d1929dd
  mch_id: 1441663202
  app_key: wqejhjksadl0o8730hjUJjsalkdawoo0
  nonce_str: jianpan